### ISSUE TITLE
Missing taxa

### ISSUE THREAD

**Issue by seltmann** [seltmann/vampire-moth-globi#3]
@jhpoelen some of the relationships are not showing up. One example is _Calyptra thalictri_ https://www.gbif.org/species/110462373

It is showing up in various lists on globi, but its not showing up in the search or in the visualizations.

**Comment by jhpoelen** [comment]
@seltmann thanks for letting me know.

GloBI currently uses GloBI taxon graph 0.3.6 with https://doi.org/10.5281/zenodo.1412873 . 

In this taxon graph, the taxonMap.tsv.gz contains entries for _Calyptra thalictri_  . Notice how some verbatim names have an extra whitespace, causing in seemingly duplicate entries. However, the resolved name do not contain the extra whitespace.


providedId | providedName | resolvedId | resolvedName
-- | -- | -- | --
https://www.gbif.org/species/110462373 | Calyptra  thalictri | EOL:545931 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra thalictri | EOL:545931 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra  thalictri | GBIF:1777631 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra thalictri | GBIF:1777631 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra  thalictri | IRMNG:11065490 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra thalictri | IRMNG:11065490 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra  thalictri | NCBI:465833 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra thalictri | NCBI:465833 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra  thalictri | OTT:412388 | Calyptra thalictri
https://www.gbif.org/species/110462373 | Calyptra thalictri | OTT:412388 | Calyptra thalictri
https://www.gbif.org/species/1777631 | Calyptra thalictri | EOL:545931 | Calyptra thalictri
https://www.gbif.org/species/1777631 | Calyptra thalictri | GBIF:1777631 | Calyptra thalictri
https://www.gbif.org/species/1777631 | Calyptra thalictri | IRMNG:11065490 | Calyptra thalictri
https://www.gbif.org/species/1777631 | Calyptra thalictri | NCBI:465833 | Calyptra thalictri
https://www.gbif.org/species/1777631 | Calyptra thalictri | OTT:412388 | Calyptra thalictri

The taxon cache also contains Calyptra thalictri entries: 

EOL:545931 | Calyptra thalictri | species | Wiesenrauten-Kapuzeneule @de \| vampire moth @en \| Kyynelyökkönen @fi \| | Animalia \| Arthropoda \| Insecta \| Lepidoptera \| Noctuoidea \| Noctuidae \| Calyptra \| Calyptra thalictri | EOL:1 \| EOL:164 \| EOL:344 \| EOL:747 \| EOL:769 \| EOL:873 \| EOL:68102 \| EOL:545931 | kingdom \| phylum \| class \| order \| superfamily \| family \| genus \| species | http://eol.org/pages/545931 | http://media.eol.org/content/2011/10/06/00/29537_98_68.jpg
-- | -- | -- | -- | -- | -- | -- | -- | --
GBIF:1777631 | Calyptra thalictri | species |   | Animalia \| Arthropoda \| Insecta \| Lepidoptera \| Noctuidae \| Calyptra \| Calyptra thalictri | GBIF:1 \| GBIF:54 \| GBIF:216 \| GBIF:797 \| GBIF:7015 \| GBIF:1777629 \| GBIF:1777631 | kingdom \| phylum \| class \| order \| family \| genus \| species | http://www.gbif.org/species/1777631 |  
IRMNG:11065490 | Calyptra thalictri | species |   | Animalia \| Arthropoda \| Insecta \| Lepidoptera \| Noctuidae \| Calyptra \| Calyptra thalictri | IRMNG:11 \| IRMNG:235 \| IRMNG:1096 \| IRMNG:12144 \| IRMNG:114179 \| IRMNG:1303485 \| IRMNG:11065490 | kingdom \| phylum \| class \| order \| family \| genus \| species | http://www.marine.csiro.au/mirrorsearch/ir_search.list_species?sp_id=11065490 |  
NCBI:465833 | Calyptra thalictri | species |   | \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Holometabola \| Amphiesmenoptera \| Lepidoptera \| Glossata \| Neolepidoptera \| Heteroneura \| Ditrysia \| Obtectomera \| Noctuoidea \| Noctuidae \| Catocalinae \| Calyptra \| Calyptra thalictri | NCBI:131567 \| NCBI:2759 \| NCBI:33154 \| NCBI:33208 \| NCBI:6072 \| NCBI:33213 \| NCBI:33317 \| NCBI:1206794 \| NCBI:88770 \| NCBI:6656 \| NCBI:197563 \| NCBI:197562 \| NCBI:6960 \| NCBI:50557 \| NCBI:85512 \| NCBI:7496 \| NCBI:33340 \| NCBI:33392 \| NCBI:85604 \| NCBI:7088 \| NCBI:41191 \| NCBI:41196 \| NCBI:41197 \| NCBI:37567 \| NCBI:104431 \| NCBI:37570 \| NCBI:7100 \| NCBI:95194 \| NCBI:465832 \| NCBI:465833 | \|  \|  \| kingdom \|  \|  \|  \|  \|  \| phylum \|  \|  \| subphylum \| class \|  \| subclass \| infraclass \| cohort \|  \| order \| suborder \| infraorder \| parvorder \|  \|  \| superfamily \| family \| subfamily \| genus \| species | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=465833 |  
OTT:412388 | Calyptra thalictri | species |   | \|  \| Eukaryota \| Opisthokonta \| Holozoa \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Amphiesmenoptera \| Lepidoptera \| Glossata \| Neolepidoptera \| Heteroneura \| Ditrysia \| Obtectomera \| Noctuoidea \| Noctuidae \| Catocalinae \| Calyptra \| Calyptra thalictri | OTT:805080 \| OTT:93302 \| OTT:304358 \| OTT:332573 \| OTT:5246131 \| OTT:691846 \| OTT:641038 \| OTT:117569 \| OTT:189832 \| OTT:611099 \| OTT:816442 \| OTT:632179 \| OTT:985907 \| OTT:985906 \| OTT:568991 \| OTT:1062253 \| OTT:983656 \| OTT:1048707 \| OTT:815350 \| OTT:1082885 \| OTT:436623 \| OTT:965954 \| OTT:89155 \| OTT:89151 \| OTT:795150 \| OTT:596629 \| OTT:371732 \| OTT:675124 \| OTT:742352 \| OTT:920401 \| OTT:412387 \| OTT:412388 | \|  \| domain \|  \|  \| kingdom \|  \|  \|  \|  \|  \| phylum \|  \|  \| superclass \| class \|  \| subclass \| subclass \| infraclass \| superorder \| order \| suborder \| infraorder \| parvorder \|  \|  \| superfamily \| family \| subfamily \| genus \| species | https://tree.opentreeoflife.org/opentree/ottol@412388 |  
WD:Q1315850 | Calyptra thalictri | species |   | \| Calyptra thalictri | WD:Q1949541 \| WD:Q1315850 | \| species | https://www.wikidata.org/wiki/Q1315850 |  

However, as you noticed, the _Calyptra thalictri_, cannot be searched, but show up in an a "download details" via https://www.globalbioticinteractions.org/browse/index.html?accordingTo=globi%3Aseltmann%2Fvampire-moth-globi&interactionType=interactsWith&resultType=json . (see attached 
[interaction_vampire_moths.csv.txt](https://github.com/seltmann/vampire-moth-globi/files/2394695/interaction_vampire_moths.csv.txt)). Notice that the same appears to be happening with _Calyptra  orthograpta_ (notice the extra space). 


This suggests that the process of ingesting GloBI taxon graph is failing to match the name somehow. Will try to reproduce and share my results.

**Comment by seltmann** [comment]
@jhpoelen Got it. I think I removed all of the double spaces. Will see how the next import goes.

**Comment by jhpoelen** [comment]
@seltmann GloBI should be able to deal with extra whitespaces and has in the past. Am re-opening issue until I can reproduce and fix the issue.

**Comment by jhpoelen** [comment]
@seltmann I found some unrelated issues that caused the automated dataset import of GloBI to be interrupted. Lets keep this open as a reminder to confirm that a successful import will resolve this naming issue. Thanks for being patient.

**Comment by jhpoelen** [comment]
@seltmann after some digging, I found that GloBI was *not* using Taxon Graph v0.3.6 , but another version that did not include any _Calyptra thalictri_ mappings. So, GloBI is working as expected and I am rebuilding GloBI with the proper version . . . thanks for being patient .

**Comment by jhpoelen** [comment]
The changes have propagated and . . . the vampire moths are among us (see screenshot) Please confirm that the names now resolve as expected.

![screenshot from 2018-09-21 10-54-55](https://user-images.githubusercontent.com/1084872/45897796-f64b4800-bd8c-11e8-8a05-8fed21166d69.png)

**Comment by seltmann** [comment]
@jhpoelen looks good. I see new issues with names but those are things like a sea snail with the same genus name as a fig tree...and I put on the wrong identifier for that name.

**Comment by seltmann** [comment]
@jhpoelen actually, just checked and the identifier for Ficus in the dataset is https://www.gbif.org/species/147211875, which is the Ficus in Plantae. There is a Ficus sea snail as well, so perhaps some name matching confusion?

**Comment by jhpoelen** [comment]
This is a known issue in handling homonyms - please see https://github.com/jhpoelen/eol-globi-data/issues/361 . Please close this issue if you agree this is a duplicate. My suspicion is that some of the homonym handling functionality got dropped when a dedicated tool, [Nomer](https://github.com/globalbioticinteractions/nomer) was introduced to do reproducible term matching. Need to have a close look.
