### ISSUE TITLE
Moved repos, now vampire-moths-and-their-fruit-piercing-relatives is out of date

### ISSUE THREAD

**Issue by seltmann** [seltmann/vampire-moth-globi#4]
@jhpoelen since I moved repos from vampire-moths-and-their-fruit-piercing-relatives to vampire-moth-globi the old repo is indexed, but out of date, and it looks like repeats of the same information.

How to fix?

**Comment by jhpoelen** [comment]
https://appear.in/jhpoelen ?

**Comment by jhpoelen** [comment]
Please see https://github.com/jhpoelen/eol-globi-data/issues/372 for a description of a feature that would accomplish this without losing a link to prior dataset. Please close this issue if you feel that the feature would cover your use case. If not, please holler.
